steps:
  # Install dependencies
  - name: 'node:25'
    entrypoint: npm
    args: ['install']

  # Install frontend dependencies and build
  - name: 'node:25'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'
  
  - name: 'node:25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend && \
        echo "REACT_APP_API_URL=https://tastytrade-459820.ue.r.appspot.com" > .env.production && \
        npm run build

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['TASTYTRADE_ACCOUNT_NUMBER']
    args:
      - '-c'
      - |
        sed -i'.bak' "s/NODE_ENV: .*/NODE_ENV: \"production\"\\n  TASTYTRADE_ACCOUNT_NUMBER: \"$$TASTYTRADE_ACCOUNT_NUMBER\"/" app.yaml && \
        gcloud app deploy app.yaml \
          --quiet \
          --project tastytrade-459820

availableSecrets:
  secretManager:
    - versionName: projects/tastytrade-459820/secrets/TASTYTRADE_ACCOUNT_NUMBER/versions/latest
      env: 'TASTYTRADE_ACCOUNT_NUMBER'
